stages:
  - build

before_script:
  - echo "+++++++++++++++++++++ 开始构建 +++++++++++++++++++++++++++++++++"
  - source ~/.bashrc

build-job:
  stage: build
  only:
    - main
  tags:
    - sit
  script:
    - nvm -v
    - node -v
    - yarn -v
    - yarn
    - echo "=============================== 开始打包 ======================================== "
    - yarn build
    - ls
    - echo "=============================== 打包完成 ======================================== "
    - zip -r dist.zip dist # 压缩
    - scp dist.zip appadmin@172.17.8.195:/data/web/sxzq # 上传
    - ssh appadmin@172.17.8.195 "cd /data/web/sxzq;mv platform platform$(date +%y%m%d%H%M);unzip dist.zip && mv dist platform;" # 替换包
    - echo “=============================== 发布完成 ======================================== ”
  artifacts: # 保留打好的包,可在job页面下载
    name: "dist"
    paths: 
      - dist/