stages:
  - build

before_script:
  - echo "+++++++++++++++++++++ 开始构建 +++++++++++++++++++++++++++++++++"
  - source ~/.bashrc

build-job:
  stage: build
  only:
    - main
  tags:
    - sit
  script:
    - yarn
    - echo "=============================== 开始打包 ======================================== "
    - yarn build
    - ls
    - echo "=============================== 打包完成 ======================================== "
    - yarn tosit
    - echo “=============================== 发布完成 ======================================== ”
  artifacts:
    name: "dist"
    paths: 
      - dist/